#!/usr/bin/env bash

deindent () {
    sed -E "s/^ {$1}//"
}

deindent 4 <<EOF
    ![ruch logo](logo.svg?raw=true)

    <p align="center">
      <code>ruch</code> is small, simple and yet effective traffic generator</br>
        <b>and it's also awesome</b>
    </p>

    # Building

    ## Quick and fast with gcc
    
    \`ruch\` has no dependencies and it is a single .c file.
    You can simply build it using gcc
    \`\`\`
    $ gcc ruch.c -o ruch
    \`\`\`

    ## CMake

    You can also build it using [cmake](https://cmake.org).

    \`\`\`console
    $ mkdir -p build
    $ cd build
    $ cmake .. && cmake --build .
    \`\`\`

    The executable will be available at

    \`\`\`console
    $ build/ruch
    \`\`\`

    # Usage

    Send 1mbit/s UDP traffic from \`10.0.0.1:1234\` to \`10.0.0.2:4321\` through \`eth0_0\` device
    \`\`\`
    ruch eth type ip ip s 10.0.0.1 d 10.0.0.2 proto udp udp s 1234 d 4321 len 1000 dev eth0_0 rate $((1024 * 1024 * 1024))
    \`\`\`

    ## Available options
    \`\`\`console
    $ ruch
EOF
    build/ruch
deindent 4 <<EOF
    \`\`\`

    # License

    \`ruch\` is licensed under GPL. See [LICENSE](LICENSE)
    for details.
EOF
