#!/usr/bin/env bash

deindent () {
    sed -E "s/^ {$1}//"
}

deindent 4 <<EOF
    ![ruch logo](logo.svg?raw=true)

    <p align="center">
      <code>ruch</code> is small, simple and yet effective traffic generator</br>
        <b>and it's also awesome</b>
    </p>

    # Building

    \`\`\`console
    $ mkdir -p build
    $ cd build
    $ cmake .. && cmake --build .
    \`\`\`

    The executable will be available at

    \`\`\`console
    $ build/ruch
    \`\`\`

    # Usage

    ## Available options
    \`\`\`console
    $ ruch
EOF
    build/ruch
deindent 4 <<EOF
    \`\`\`

    # License

    \`ruch\` is licensed under GPL. See [LICENSE](LICENSE)
    for details.
EOF
